openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Buy or rent spacecrafts

paths:
  /users:
    post:
      summary: Añadir un usuario nuevo a la red
      responses:
        '200':
          description: User with 'username' added
    get:
      summary: Obtener una lista de todos los usuarios existentes en la red social. Esta lista debe permitir ser filtrada por patrón de nombre (eg. Buscar todos los usuarios que contengan “Mar” en su nombre, “Mario”, “Maria”…etc.)
      responses:
        '200':
          description: User with 'username' added

  /users/{id}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
    get:
      summary: Ver los datos básicos de un usuario
      responses:
        '200':
          description: User with 'username' added

    put:
      summary: Cambiar datos básicos de nuestro perfil de usuario
      responses:
        '200':
          description: User with 'username' added
    delete:
      summary: Borrar nuestro perfil de la red social
      
  /users/{id}/friends:
    post:
      summary: Añadir un nuevo amigo de entre los usuarios registrados en la red social
    get:
      summary: Obtener una lista de todos nuestros amigos. Además, esta lista debe permitir la opción de ser filtrada por el patrón de nombre o limitar la cantidad de información obtenida por número de amigos (e.g. los 10 primeros elementos, los elementos entre el 11 y el 20, etc.)
      
  /users/{id}/friends/{friend_id}:
    delete:
      summary: Eliminar un amigo
      
  /users/{id}/messages:
    post:
      summary: Un usuario puede publicar un nuevo mensaje en su página personal
    get:
      summary: Obtener una lista de todos los mensajes escritos por un usuario en su página personal. Además, esta lista debe permitir la opción de ser filtrada por fecha o limitar la cantidad de información obtenida por número (e.g. los 10 primeros elementos, los elementos entre el 11 y el 20, etc.)
      
  /users/{id}/messages/{message_id}:
    put:
      summary: Un usuario puede editar un mensaje de su página personal
    delete:
      summary: Un usuario puede eliminar un mensaje de su página personal
    get:
      summary: Obtener detalles sobre un mensaje específico
      
  /users/{id}/messages/friends:
    get:
      summary: Consultar los últimos mensajes publicados de nuestros amigos en su página personal obtener una lista de los últimos mensajes de todos mis amigos, pudiendo filtrar estos mensajes por fecha (último antes de cierta fecha). Poder limitar la cantidad de información obtenida por número.
      
  /users/{id}/messages/friends/search:
    get:
      summary: Buscar en todos los mensajes de nuestros amigos por contenido –contiene un determinado texto-. Poder limitar la cantidad de información obtenida por número.

  /description:
    get:
      summary: Consultar fácilmente la descripción necesaria para una aplicación móvil que queremos realizar, que muestre los datos básicos de un usuario, su último mensaje de su página, el número de amigos y los mensajes de sus 10 últimos amigos que se han actualizado (escritos por ellos mismos en su página personal de la red social)